
on: 
  release:
    types: [created]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: altipla-consulting/altipla.actions/go-release-1.14@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMAND: ./cmd/jnet

    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: altipla/jnet
        tag_with_ref: true

    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: altipla/jnet
        tags: latest
